export type MlbTeam = {
  id: number;
  name: string;
  zh: string;
  short: string;
  abbreviation: string;
  league: "AL" | "NL";
  division: "East" | "Central" | "West";
  logo: string;
};

export const MLB_TEAMS: Record<number, MlbTeam> = {
  108: {
    id: 108,
    name: "Los Angeles Angels",
    zh: "洛杉磯天使",
    short: "天使",
    abbreviation: "LAA",
    league: "AL",
    division: "West",
    logo: "https://www.mlbstatic.com/team-logos/108.svg",
  },
  109: {
    id: 109,
    name: "Arizona Diamondbacks",
    zh: "亞利桑那響尾蛇",
    short: "響尾蛇",
    abbreviation: "AZ",
    league: "NL",
    division: "West",
    logo: "https://www.mlbstatic.com/team-logos/109.svg",
  },
  110: {
    id: 110,
    name: "Baltimore Orioles",
    zh: "巴爾的摩金鶯",
    short: "金鶯",
    abbreviation: "BAL",
    league: "AL",
    division: "East",
    logo: "https://www.mlbstatic.com/team-logos/110.svg",
  },
  111: {
    id: 111,
    name: "Boston Red Sox",
    zh: "波士頓紅襪",
    short: "紅襪",
    abbreviation: "BOS",
    league: "AL",
    division: "East",
    logo: "https://www.mlbstatic.com/team-logos/111.svg",
  },
  112: {
    id: 112,
    name: "Chicago Cubs",
    zh: "芝加哥小熊",
    short: "小熊",
    abbreviation: "CHC",
    league: "NL",
    division: "Central",
    logo: "https://www.mlbstatic.com/team-logos/112.svg",
  },
  113: {
    id: 113,
    name: "Cincinnati Reds",
    zh: "辛辛那提紅人",
    short: "紅人",
    abbreviation: "CIN",
    league: "NL",
    division: "Central",
    logo: "https://www.mlbstatic.com/team-logos/113.svg",
  },
  114: {
    id: 114,
    name: "Cleveland Guardians",
    zh: "克里夫蘭守護者",
    short: "守護者",
    abbreviation: "CLE",
    league: "AL",
    division: "Central",
    logo: "https://www.mlbstatic.com/team-logos/114.svg",
  },
  115: {
    id: 115,
    name: "Colorado Rockies",
    zh: "科羅拉多洛磯",
    short: "洛磯",
    abbreviation: "COL",
    league: "NL",
    division: "West",
    logo: "https://www.mlbstatic.com/team-logos/115.svg",
  },
  116: {
    id: 116,
    name: "Detroit Tigers",
    zh: "底特律老虎",
    short: "老虎",
    abbreviation: "DET",
    league: "AL",
    division: "Central",
    logo: "https://www.mlbstatic.com/team-logos/116.svg",
  },
  117: {
    id: 117,
    name: "Houston Astros",
    zh: "休士頓太空人",
    short: "太空人",
    abbreviation: "HOU",
    league: "AL",
    division: "West",
    logo: "https://www.mlbstatic.com/team-logos/117.svg",
  },
  118: {
    id: 118,
    name: "Kansas City Royals",
    zh: "堪薩斯市皇家",
    short: "皇家",
    abbreviation: "KC",
    league: "AL",
    division: "Central",
    logo: "https://www.mlbstatic.com/team-logos/118.svg",
  },
  119: {
    id: 119,
    name: "Los Angeles Dodgers",
    zh: "洛杉磯道奇",
    short: "道奇",
    abbreviation: "LAD",
    league: "NL",
    division: "West",
    logo: "https://www.mlbstatic.com/team-logos/119.svg",
  },
  120: {
    id: 120,
    name: "Washington Nationals",
    zh: "華盛頓國民",
    short: "國民",
    abbreviation: "WSH",
    league: "NL",
    division: "East",
    logo: "https://www.mlbstatic.com/team-logos/120.svg",
  },
  121: {
    id: 121,
    name: "New York Mets",
    zh: "紐約大都會",
    short: "大都會",
    abbreviation: "NYM",
    league: "NL",
    division: "East",
    logo: "https://www.mlbstatic.com/team-logos/121.svg",
  },
  133: {
    id: 133,
    name: "Athletics",
    zh: "運動家",
    short: "運動家",
    abbreviation: "ATH",
    league: "AL",
    division: "West",
    logo: "https://www.mlbstatic.com/team-logos/133.svg",
  },
  134: {
    id: 134,
    name: "Pittsburgh Pirates",
    zh: "匹茲堡海盜",
    short: "海盜",
    abbreviation: "PIT",
    league: "NL",
    division: "Central",
    logo: "https://www.mlbstatic.com/team-logos/134.svg",
  },
  135: {
    id: 135,
    name: "San Diego Padres",
    zh: "聖地牙哥教士",
    short: "教士",
    abbreviation: "SD",
    league: "NL",
    division: "West",
    logo: "https://www.mlbstatic.com/team-logos/135.svg",
  },
  136: {
    id: 136,
    name: "Seattle Mariners",
    zh: "西雅圖水手",
    short: "水手",
    abbreviation: "SEA",
    league: "AL",
    division: "West",
    logo: "https://www.mlbstatic.com/team-logos/136.svg",
  },
  137: {
    id: 137,
    name: "San Francisco Giants",
    zh: "舊金山巨人",
    short: "巨人",
    abbreviation: "SF",
    league: "NL",
    division: "West",
    logo: "https://www.mlbstatic.com/team-logos/137.svg",
  },
  138: {
    id: 138,
    name: "St. Louis Cardinals",
    zh: "聖路易紅雀",
    short: "紅雀",
    abbreviation: "STL",
    league: "NL",
    division: "Central",
    logo: "https://www.mlbstatic.com/team-logos/138.svg",
  },
  139: {
    id: 139,
    name: "Tampa Bay Rays",
    zh: "坦帕灣光芒",
    short: "光芒",
    abbreviation: "TB",
    league: "AL",
    division: "East",
    logo: "https://www.mlbstatic.com/team-logos/139.svg",
  },
  140: {
    id: 140,
    name: "Texas Rangers",
    zh: "德州遊騎兵",
    short: "遊騎兵",
    abbreviation: "TEX",
    league: "AL",
    division: "West",
    logo: "https://www.mlbstatic.com/team-logos/140.svg",
  },
  141: {
    id: 141,
    name: "Toronto Blue Jays",
    zh: "多倫多藍鳥",
    short: "藍鳥",
    abbreviation: "TOR",
    league: "AL",
    division: "East",
    logo: "https://www.mlbstatic.com/team-logos/141.svg",
  },
  142: {
    id: 142,
    name: "Minnesota Twins",
    zh: "明尼蘇達雙城",
    short: "雙城",
    abbreviation: "MIN",
    league: "AL",
    division: "Central",
    logo: "https://www.mlbstatic.com/team-logos/142.svg",
  },
  143: {
    id: 143,
    name: "Philadelphia Phillies",
    zh: "費城費城人",
    short: "費城人",
    abbreviation: "PHI",
    league: "NL",
    division: "East",
    logo: "https://www.mlbstatic.com/team-logos/143.svg",
  },
  144: {
    id: 144,
    name: "Atlanta Braves",
    zh: "亞特蘭大勇士",
    short: "勇士",
    abbreviation: "ATL",
    league: "NL",
    division: "East",
    logo: "https://www.mlbstatic.com/team-logos/144.svg",
  },
  145: {
    id: 145,
    name: "Chicago White Sox",
    zh: "芝加哥白襪",
    short: "白襪",
    abbreviation: "CWS",
    league: "AL",
    division: "Central",
    logo: "https://www.mlbstatic.com/team-logos/145.svg",
  },
  146: {
    id: 146,
    name: "Miami Marlins",
    zh: "邁阿密馬林魚",
    short: "馬林魚",
    abbreviation: "MIA",
    league: "NL",
    division: "East",
    logo: "https://www.mlbstatic.com/team-logos/146.svg",
  },
  147: {
    id: 147,
    name: "New York Yankees",
    zh: "紐約洋基",
    short: "洋基",
    abbreviation: "NYY",
    league: "AL",
    division: "East",
    logo: "https://www.mlbstatic.com/team-logos/147.svg",
  },
  158: {
    id: 158,
    name: "Milwaukee Brewers",
    zh: "密爾瓦基釀酒人",
    short: "釀酒人",
    abbreviation: "MIL",
    league: "NL",
    division: "Central",
    logo: "https://www.mlbstatic.com/team-logos/158.svg",
  },
};

export function getMlbTeam(teamId: number): MlbTeam | undefined {
  return MLB_TEAMS[teamId];
}

export function getMlbTeamName(teamId: number): string {
  return MLB_TEAMS[teamId]?.zh ?? "未知球隊";
}

export function getMlbTeamShortName(teamId: number): string {
  return MLB_TEAMS[teamId]?.short ?? "未知球隊";
}

export function getMlbTeamLogo(teamId: number): string {
  return (
    MLB_TEAMS[teamId]?.logo ??
    `https://www.mlbstatic.com/team-logos/${teamId}.svg`
  );
}